---
abstract: 'A Dictionary for the Sindarin language'
author:
  - 'Felipe da Veiga Leprevost <leprevost@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-Sindarin-Dictionary
no_index:
  directory:
    - t
    - inc
requires:
  Moose: '0'
  namespace::autoclean: '0'
  perl: '5.006'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Lingua-Sindarin-Dictionary
  homepage: https://github.com/Leprevost/Lingua-Sindarin-Dictionary
  repository: https://github.com/Leprevost/Lingua-Sindarin-Dictionary.git
version: '0.01'
